### ISSUE TITLE
Does not build after drinking wine

### ISSUE THREAD

**Issue by CaptainAchilles** [matthew-matvei/compair#1]
After drinking `wine`, the project will no longer build.

**Comment by matthew-matvei** [comment]
Unfortunately, prior to and / or after drinking any alcoholic drink, it does not build due to incorrect types brought in by some libraries.

The solution may be to allow emitting 'on errors'. What I'd rather is to be able to ignore errors specifically within node_modules. But yeah, this needs dealing with.

**Comment by matthew-matvei** [comment]
Examining this uncovered the fact that the `material-ui` package was never placed in the list of `dependencies` (using a pre-v5 `npm` at home, forgot the `--save` flag ;) ). It will be in an imminent pull request.

The offending library, however, is `rc-tooltip`, whose types (`@types/rc-tooltip`) even at the same version do not quite marry up properly with the actual behaviour of the library. Temporarily, you would need to change the last three lines of `/node_modules/@types/rc-tooltip/index.d.ts` to:

``` typescript
declare module "rc-tooltip" {
    export default Tooltip
}
```

I'm raising this with them, too.

Note that with the current build setup, you should still have a perfectly usable `dist/out.js` file.

**Comment by matthew-matvei** [comment]
I've created [the issue on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19372) and have merged in a 'fix' for this. However, the build process will still complain about problems with types (though should still emit valid output).

Will close this unless you have any issues with it.

**Comment by matthew-matvei** [comment]
This issue has been fixed upstream and the dependency has been updated in this project, closing this.
